#!/usr/bin/env python3
"""Build dist/steve-full.md — the whole skill as one pasteable file.

Inside Claude Code the skill loads its references on demand, which is why
SKILL.md is short. In a chat window there is nothing to load from, so a paste
of SKILL.md alone gives the rules and none of the templates. This script
flattens the folder into one document that works when pasted anywhere.

Run: python3 scripts/build_single_file.py
"""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL_DIR = ROOT / "skills" / "steve"
OUT = ROOT / "dist" / "steve-full.md"

ORDER = [
    "references/playbooks/verdict.md",
    "references/playbooks/why.md",
    "references/playbooks/cut.md",
    "references/playbooks/next.md",
    "references/playbooks/pitch.md",
    "references/playbooks/email.md",
    "references/voice.md",
    "references/quotes.md",
    "references/principles.md",
    "references/episodes.md",
    "references/failures.md",
]

HEADER = """<!--
  Ask Steve — the whole skill in one file.
  Generated by scripts/build_single_file.py. Do not edit this file; edit
  skills/steve/ and rebuild.

  Paste this into any chat window as a system prompt, or into an agent that
  cannot read a folder. Inside Claude Code, install the folder instead: the
  references there load only when a mode needs them, which is cheaper.

  https://github.com/bergamett/steve-jobs-skill
-->

"""


def strip_frontmatter(text: str) -> str:
    if text.startswith("---\n"):
        return text.split("---", 2)[2].lstrip("\n")
    return text


def main() -> int:
    skill = strip_frontmatter((SKILL_DIR / "SKILL.md").read_text(encoding="utf-8"))
    # In a single file there is nothing to load; say so where the skill says to load.
    skill = skill.replace(
        "The playbooks are short and each one owns its output template. Read the one you need every time.",
        "The playbooks are short and each one owns its output template. In this single-file version they are "
        "further down this document under their own headings; find the one you need and follow it.",
    )
    parts = [HEADER, skill, "\n\n---\n"]
    for rel in ORDER:
        path = SKILL_DIR / rel
        body = strip_frontmatter(path.read_text(encoding="utf-8"))
        parts.append(f"\n<!-- {rel} -->\n\n{body}\n\n---\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    n_lines = len(OUT.read_text(encoding="utf-8").split("\n"))
    n_words = len(OUT.read_text(encoding="utf-8").split())
    print(f"wrote {OUT.relative_to(ROOT)}: {n_lines} lines, ~{n_words} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
